services:
  postgres:
    image: postgres:16
    container_name: pms_postgres
    restart: always
    env_file: .env
    volumes:
      - pms_postgres_data:/var/lib/postgresql/data
    networks:
      - pms_network

  redis:
    image: redis:7-alpine
    container_name: pms_redis
    restart: always
    networks:
      - pms_network

  django:
    build: .
    container_name: pms_django
    image: pms_django
    restart: always
    command: sh -c "python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8000 root.wsgi:application"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - pms_logs:/app/logs   # Filebeat shu yerdan o'qiydi
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - pms_network

  celery:
    image: pms_django
    container_name: pms_celery
    restart: always
    command: celery -A root worker -l info
    volumes:
      - .:/app
      - pms_logs:/app/logs
    env_file:
      - .env
    depends_on:
      - django
      - redis
      - postgres
    networks:
      - pms_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: pms_elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - pms_network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: pms_kibana
    restart: always
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - pms_network

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.15.0
    container_name: pms_filebeat
    user: root
    restart: always
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - pms_logs:/logs:ro
    depends_on:
      - elasticsearch
      - django
    networks:
      - pms_network

volumes:
  pms_postgres_data:
  static_volume:
  es_data:
  pms_logs:

networks:
  pms_network:
    driver: bridge