services:
  postgres:
    image: postgres:16
    container_name: pms_postgres
    restart: always
    env_file: .env
    volumes:
      - pms_postgres_data:/var/lib/postgresql/data
    networks:
      - pms_network

  redis:
    image: redis:7-alpine
    container_name: pms_redis
    restart: always
    networks:
      - pms_network

  django:
    build: .
    container_name: pms_django
    image: pms_django
    restart: always
    command: sh -c "python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - pms_logs:/app/logs
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - pms_network

  celery:
    image: pms_django
    container_name: pms_celery
    restart: always
    command: celery -A root worker -l info
    volumes:
      - .:/app
      - pms_logs:/app/logs
    env_file:
      - .env
    depends_on:
      - django
      - redis
      - postgres
    networks:
      - pms_network

volumes:
  pms_postgres_data:
  static_volume:
  pms_logs:
    external: true

networks:
  pms_network:
    external: true

