# Generated by Django 6.0.7 on 2026-07-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtypebase',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomtypebase',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance'), ('cleaning', 'Cleaning'), ('out_of_service', 'OUT_OF_SERVICE')], default='available', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('room_number',), name='unique_active_room_number'),
        ),
        migrations.AlterModelTable(
            name='room',
            table='rooms',
        ),
        migrations.AlterModelTable(
            name='roominventory',
            table='room_inventories',
        ),
        migrations.AlterModelTable(
            name='roomtype',
            table='room_types',
        ),
        migrations.AlterModelTable(
            name='roomtypebase',
            table='room_type_bases',
        ),
    ]
