# Generated by Django 6.0.7 on 2026-07-15 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_room_deleted_at_room_is_deleted_roomtype_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roominventory',
            options={'verbose_name_plural': 'Room Inventories'},
        ),
    ]
