# Generated by Django 6.0.7 on 2026-07-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_alter_roominventory_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='room',
            name='unique_active_room_number',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='roomtypebase',
            name='is_deleted',
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at', None)), fields=('room_number',), name='unique_active_room_number'),
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_deleted',
        ),
    ]
