# Generated by Django 6.0.7 on 2026-07-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_remove_room_unique_active_room_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roominventory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
