# Generated by Django 6.0.7 on 2026-08-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_roominventory_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='max_occupancy',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
