# Generated by Django 6.0.7 on 2026-08-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('passport', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'guests',
            },
        ),
        migrations.AddConstraint(
            model_name='guest',
            constraint=models.UniqueConstraint(condition=~models.Q(('passport', '')), fields=('passport',), name='unique_guest_passport_when_present'),
        ),
    ]
