
from django.utils.translation import gettext_lazy as _

class RoomStatus:
    AVAILABLE = _("AVAILABLE")
    OCCUPIED = _("OCCUPIED")
    CLEANING = _("CLEANING")
    MAINTENANCE = _("MAINTENANCE")
    OUT_OF_SERVICE = _("OUT_OF_SERVICE")

    CHOICES = (AVAILABLE, OCCUPIED, CLEANING, MAINTENANCE, OUT_OF_SERVICE)

    UNBOOKABLE = {CLEANING, MAINTENANCE, OUT_OF_SERVICE}

    ALLOWED_TRANSITIONS = {
        AVAILABLE: {OCCUPIED, MAINTENANCE, OUT_OF_SERVICE},
        OCCUPIED: {CLEANING, MAINTENANCE},
        CLEANING: {AVAILABLE, MAINTENANCE},
        MAINTENANCE: {AVAILABLE, OUT_OF_SERVICE},
        OUT_OF_SERVICE: {MAINTENANCE, AVAILABLE},
    }


