from apps.room.models import Room


class RoomStatus:
    AVAILABLE = Room.Status.AVAILABLE
    OCCUPIED = Room.Status.OCCUPIED
    CLEANING = Room.Status.CLEANING
    MAINTENANCE = Room.Status.MAINTENANCE
    OUT_OF_SERVICE = Room.Status.OUT_OF_SERVICE

    CHOICES = (AVAILABLE, OCCUPIED, CLEANING, MAINTENANCE, OUT_OF_SERVICE)

    UNBOOKABLE = {CLEANING, MAINTENANCE, OUT_OF_SERVICE}

    ALLOWED_TRANSITIONS = {
        AVAILABLE: {OCCUPIED, MAINTENANCE, OUT_OF_SERVICE},
        OCCUPIED: {CLEANING, MAINTENANCE},
        CLEANING: {AVAILABLE, MAINTENANCE},
        MAINTENANCE: {AVAILABLE, OUT_OF_SERVICE},
        OUT_OF_SERVICE: {MAINTENANCE, AVAILABLE},
    }
