# Generated by Django 6.0.7 on 2026-07-14 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reservation',
            table='reservations',
        ),
    ]
