# Generated by Django 6.0.7 on 2026-07-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_reservation_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='guest_name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
