# Generated by Django 6.0.7 on 2026-07-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_reservation_guest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='guest_name',
            field=models.CharField(max_length=25),
        ),
        # migrations.RunSQL(
        #     sql="drop index reservation_guest_name_3c2d7750_like"
        # )
    ]
