# Generated by Django 6.0.7 on 2026-08-10 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
        ('reservation', '0004_alter_reservation_guest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guest',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='reservations',
                to='guest.guest',
            ),
        ),
    ]
