# Generated by Django 6.0.7 on 2026-08-10 00:02
"""Data migration: every existing reservation.guest_name is turned into a
Guest row (created or reused by full_name) and reservation.guest is pointed
at it. Legacy rows have no country/birthday/passport, so those are left
blank on the created Guest — they can be filled in later (e.g. at check-in).

Note: reservations that already share the same guest_name are merged onto
a single Guest row here. That's a reasonable default for this backfill, but
isn't guaranteed to be correct (two different people can share a name).
"""

from django.db import migrations


def migrate_guest_names_forward(apps, schema_editor):
    Reservation = apps.get_model('reservation', 'Reservation')
    Guest = apps.get_model('guest', 'Guest')

    guest_cache = {}
    for reservation in Reservation.objects.filter(guest__isnull=True).iterator():
        name = (reservation.guest_name or "").strip() or "Unknown Guest"
        guest_id = guest_cache.get(name)
        if guest_id is None:
            guest, _created = Guest.objects.get_or_create(
                full_name=name,
                defaults={"country": "", "birthday": None, "passport": ""},
            )
            guest_id = guest.id
            guest_cache[name] = guest_id
        reservation.guest_id = guest_id
        reservation.save(update_fields=["guest"])


def migrate_guest_names_backward(apps, schema_editor):
    Reservation = apps.get_model('reservation', 'Reservation')
    for reservation in Reservation.objects.select_related('guest').filter(guest__isnull=False).iterator():
        reservation.guest_name = reservation.guest.full_name[:25]
        reservation.save(update_fields=["guest_name"])


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_reservation_guest'),
    ]

    operations = [
        migrations.RunPython(migrate_guest_names_forward, migrate_guest_names_backward),
    ]
