# Generated by Django 6.0.7 on 2026-08-10 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_backfill_reservation_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='guest_name',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='reservations',
                to='guest.guest',
            ),
        ),
    ]
