# Generated by Django 6.0.7 on 2026-08-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_reservation_guest_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guest_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
