# Generated by Django 6.0.7 on 2026-08-11 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_reservation_guest_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='guest',
            new_name='primary_guest',
        ),
    ]
